### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by lrhlrhlrhlrhlrh** [ZhaochongAn/COSeg#7]
I met the error when I want to train with the command saying "python train_backbone.py --config config/s3dis_COSeg_fs.yaml save_path output/backbone_1 cvfold 1":
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
已放弃 (核心已转储)
What's the matter with it? How to solve it?

**Comment by ZhaochongAn** [comment]
Hi, this issue seems to be related to an out-of-memory error. The error message std::bad_alloc indicates that the program attempted to allocate memory but failed. Could you check how much is your available memory and try to allocate more for running the code?

**Comment by lrhlrhlrhlrhlrh** [comment]
Thank you, I have solved this problem, but I met a new error, showed as this:
Traceback (most recent call last):
  File "train_backbone.py", line 838, in <module>
    main()
  File "train_backbone.py", line 108, in main
    mp.spawn(
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yetao123456/LRH/3D_detection/COSeg/train_backbone.py", line 121, in main_worker
    torch.cuda.set_device(gpu)
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

(coseg) yetao123456@yetao123456:~/LRH/3D_detection/COSeg$ CUDA_LAUNCH_BLOCKING=1 python3 train_backbone.py --config config/s3dis_stratified_pretraining.yaml save_path output/s3dis_stratified_pretraining cvfold 1
Traceback (most recent call last):
  File "train_backbone.py", line 838, in <module>
    main()
  File "train_backbone.py", line 108, in main
    mp.spawn(
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yetao123456/LRH/3D_detection/COSeg/train_backbone.py", line 121, in main_worker
    torch.cuda.set_device(gpu)
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

(coseg) yetao123456@yetao123456:~/LRH/3D_detection/COSeg$ CUDA_VISIBLE_DEVICES=0 python3 train_backbone.py --config config/s3dis_stratified_pretraining.yaml save_path output/s3dis_stratified_pretraining cvfold 1
Traceback (most recent call last):
  File "train_backbone.py", line 838, in <module>
    main()
  File "train_backbone.py", line 108, in main
    mp.spawn(
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yetao123456/LRH/3D_detection/COSeg/train_backbone.py", line 121, in main_worker
    torch.cuda.set_device(gpu)
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

(coseg) yetao123456@yetao123456:~/LRH/3D_detection/COSeg$ python train_backbone.py --config config/s3dis_stratified_pretraining.yaml save_path output/s3dis_stratified_pretraining cvfold 1
Traceback (most recent call last):
  File "train_backbone.py", line 838, in <module>
    main()
  File "train_backbone.py", line 108, in main
    mp.spawn(
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/yetao123456/LRH/3D_detection/COSeg/train_backbone.py", line 121, in main_worker
    torch.cuda.set_device(gpu)
  File "/home/yetao123456/anaconda3/envs/coseg/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by ZhaochongAn** [comment]
Hi, are you using one GPU or multiple GPUs? The default setting will use 4 GPUs. It seems that your device does not have enough GPUs for running the script.
